Travalue/Travalue-Server

build.gradle
src/main/java/com/deploy/Travalue/controller/test/TestController.java

서버 확인용 API 생성
close #2
Swagger 라이브러리 설치
테스트용 컨트롤러 & API 구현
Related to: #2

[Test] 배포 확인용 테스트 API 생성

---

appspec.yml
scripts/deploy.sh

자동 배포 세팅
close #5
appspec.yml 생성
deploy.sh 생성
Related to: #5

[Setting]: 자동 배포 세팅

---

.github/workflows/gradle.yml
appspec.yml
build.gradle
scripts/deploy.sh
src/main/java/com/deploy/Travalue/controller/test/TestController.java

서버 CI 기본 환경 세팅

---

.github/workflows/gradle.yml
appspec.yml

Setting: appspec.yml파일 수정

---

src/main/java/com/deploy/Travalue/common/dto/ApiResponse.java
src/main/java/com/deploy/Travalue/common/exception/ErrorCode.java
src/main/java/com/deploy/Travalue/common/exception/StatusCode.java
src/main/java/com/deploy/Travalue/common/exception/SuccessCode.java

ApiResponse 클래스 에러 수정
close #16 
success method 재정의
error method 재정의
Related to: #16

[setting]: ApiResponse 클래스 에러 수정

---

src/main/java/com/deploy/Travalue/common/advice/ControllerExceptionAdvice.java
src/main/java/com/deploy/Travalue/config/resolver/UserIdResolver.java
src/main/java/com/deploy/Travalue/exception/ErrorCode.java
src/main/java/com/deploy/Travalue/travel/controller/dto/request/CategoryRequestDto.java

category 생성 API 예외처리
close #34 
category 생성 API 예외처리

[update]: category 생성 API 예외처리

---

.gitignore
src/main/java/com/deploy/Travalue/common/advice/ControllerExceptionAdvice.java
src/main/java/com/deploy/Travalue/travel/controller/CategoryController.java
src/main/java/com/deploy/Travalue/travel/controller/dto/request/CategoryRequestDto.java

[feat] 카테고리 생성 API 에러 처리

---

src/main/java/com/deploy/Travalue/common/advice/ControllerExceptionAdvice.java
src/main/java/com/deploy/Travalue/common/domain/AuditingTimeEntity.java
src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/exception/model/UnauthorizedException.java
src/main/java/com/deploy/Travalue/external/client/aws/S3Service.java
src/main/java/com/deploy/Travalue/travel/controller/CategoryController.java
src/main/java/com/deploy/Travalue/travel/domain/Category.java
src/main/java/com/deploy/Travalue/travel/infrastructure/CategoryRepository.java
src/main/java/com/deploy/Travalue/travel/service/CategoryService.java

close #41 
카테고리 수정 API 구현
카테고리 삭제 API 구현
S3 객체 삭제 메서드 구현
Related to: #41

[feat] 카테고리 수정 삭제 API 구현

---

src/main/java/com/deploy/Travalue/user/controller/myTrip/MyTripController.java
src/main/java/com/deploy/Travalue/user/service/myTrip/MyTripService.java

나의 여행지 생성 API 수정
close #43 
ResponseStatus 지정
Related to: #43

[feat] 나의 여행지 생성 API 수정

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/domain/Travel.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java

트레블 삭제 API입니다
close #46
Soft Delete로 구현함에 따라 Travel Entity에 isDeleted Column이 추가되었습니다.
추후
- 조회할 때 isDeleted = False 조건 추가
- Travel 삭제에 따른 TravelPin, TravelInformation 등의 처리
가 필요합니다.

Feat: 트레블 삭제 API

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/infrastructure/TravelCustomRepository.java
src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java
src/main/java/com/deploy/Travalue/user/controller/UserController.java
src/main/java/com/deploy/Travalue/user/controller/dto/SharedTravelDetailDto.java
src/main/java/com/deploy/Travalue/user/controller/dto/UpdateProfileRequestDto.java
src/main/java/com/deploy/Travalue/user/domain/User.java
src/main/java/com/deploy/Travalue/user/service/UserService.java

- 공유 중인 여행지 전체 조회 API 구현
- 공유 중인 여행지 카테고리별 조회 API 구현
- 프로필 편집 API 구현
close #31 

Feat/#31 공유 중인 여행지 전체, 카테고리별 조회 API 구현 / 프로필 편집 API 구현

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java

Traveller 검색 API입니다.
키워드가 제목이나 부제목에 포함되어 있고, 공개 상태이고, 삭제되지 않은 게시물의 id, 썸네일을 반환합니다.
close #51

Feat: Traveller 검색 API 구현

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/HotTravellersResponseDto.java

가장 최근에 작성된 Traveller 3개를 조회합니다.
dto를 겹치는 부분만 재활용할 수 있는 방법이 있는지 궁금하네요
close #53 

Feat: 지금 핫한 Traveller 조회 API

---

src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/infrastructure/LikeTravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelResponseDto.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelStatisticsDto.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelWriterDto.java

- 상세조회 api 수정
- service 플로우 리팩토링
close #55
- 상세조회 api response에 isLiked, likeCount, viewcount를 추가했습니다.
- dto 중 일부를 Builder 패턴으로 수정했습니다

Fix: Traveller 상세조회 API 수정

---

src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/infrastructure/TravelContentRepository.java
src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java

상세조회 api의 contents를 Pin index로 정렬했습니다
close #55

Fix: contents 배열 pin index로 정렬

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/controller/likeTravel/LikeTravelController.java
src/main/java/com/deploy/Travalue/travel/domain/LikeTravel.java
src/main/java/com/deploy/Travalue/travel/infrastructure/LikeTravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java

[feat] 게시물 좋아요 & 좋아요 취소 API

---

src/main/java/com/deploy/Travalue/user/controller/AuthController.java
src/main/java/com/deploy/Travalue/user/domain/User.java
src/main/java/com/deploy/Travalue/user/dto/CreateUserDto.java
src/main/java/com/deploy/Travalue/user/dto/response/LoginResponse.java
src/main/java/com/deploy/Travalue/user/dto/response/LoginServiceResponseDto.java
src/main/java/com/deploy/Travalue/user/service/AuthService.java
src/main/java/com/deploy/Travalue/user/service/KaKaoAuthService.java
src/main/java/com/deploy/Travalue/user/service/UserService.java

[fix] 소셜 로그인 닉네임 처리 추가

---

src/main/java/com/deploy/Travalue/user/domain/SocialInformation.java
src/main/java/com/deploy/Travalue/user/domain/User.java
src/main/java/com/deploy/Travalue/user/dto/CreateUserDto.java
src/main/java/com/deploy/Travalue/user/dto/request/LoginRequest.java
src/main/java/com/deploy/Travalue/user/service/KaKaoAuthService.java

- 로그인 / 회원가입 API 
기존 : code, socialType 필요  
변경된 방식 : uniqueId, socialType, email, profileImage 필요
- socialId -> uniqueId 명칭 변경

Feat/#31 로그인 / 회원가입 로직 변경

---

src/main/java/com/deploy/Travalue/travel/controller/CategoryController.java

CategoryController.java 공백 추가
Related to: none
close #00

[Test] CI/CD 테스트

---

src/main/java/com/deploy/Travalue/exception/ErrorCode.java
src/main/java/com/deploy/Travalue/exception/model/ConflictException.java
src/main/java/com/deploy/Travalue/travel/infrastructure/LikeTravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java

게시물 좋아요 시 이미 좋아요 누른 게시글이면 에러처리
close #00

[Fix]: 게시물 좋아요 취소 기능 수정

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/travel/controller/CategoryController.java
src/main/java/com/deploy/Travalue/travel/infrastructure/CategoryRepository.java
src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/CategoryService.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/CategoryListResponseDto.java
src/main/java/com/deploy/Travalue/user/controller/UserController.java

카테고리 전체 조회 API
close #74 
카테고리 전체 조회 API

[Feat]: 카테고리 전체 조회 API

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/exception/model/ForbiddenException.java
src/main/java/com/deploy/Travalue/user/controller/myTrip/MyTripController.java
src/main/java/com/deploy/Travalue/user/infrastructure/myTrip/MyTripRepository.java
src/main/java/com/deploy/Travalue/user/service/myTrip/MyTripService.java

[Feat]:나의 여행지 삭제 API 추가

---

src/main/java/com/deploy/Travalue/travel/service/TravelService.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelStatisticsDto.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelWriterDto.java

게시물 상세조회 API에 유저의 좋아요 상태를 반영하도록 수정했습니다
close #88

[fix] 게시물 상세조회 API 유저의 좋아요 상태 반영

---

src/main/java/com/deploy/Travalue/travel/service/CategoryService.java
src/main/java/com/deploy/Travalue/travel/service/dto/response/CategoryListResponseDto.java

[Feat]: 카테고리 response에 id 추가

---

src/main/java/com/deploy/Travalue/user/controller/UserController.java
src/main/java/com/deploy/Travalue/user/controller/dto/MyPageUpdateRequestDto.java
src/main/java/com/deploy/Travalue/user/controller/dto/UpdateProfileRequestDto.java
src/main/java/com/deploy/Travalue/user/domain/User.java
src/main/java/com/deploy/Travalue/user/service/UserService.java

#92 fix my page

---

src/main/java/com/deploy/Travalue/travel/controller/TravelController.java

[Feat]: content-type 추가

---

src/main/java/com/deploy/Travalue/exception/SuccessCode.java
src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
src/main/java/com/deploy/Travalue/travel/controller/dto/request/ReportTravelRequestDto.java
src/main/java/com/deploy/Travalue/travel/domain/ReportTravel.java
src/main/java/com/deploy/Travalue/travel/infrastructure/ReportTravelRepository.java
src/main/java/com/deploy/Travalue/travel/service/TravelService.java

Feat: 게시물 신고 API 구현
